# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 10:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupno', models.PositiveIntegerField(default=0)),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='EvalPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default=b'NA')),
                ('supervisor', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
                ('isfileuploaded', models.BooleanField(default=False)),
                ('isexternal', models.BooleanField(default=False)),
                ('fileuploaded', models.FileField(blank=True, null=True, upload_to=b'')),
                ('display', models.BooleanField(default=True)),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sem', models.SmallIntegerField()),
                ('batch', models.CharField(choices=[(b'UG1', b'UG1'), (b'UG2', b'UG2'), (b'UG3', b'UG3'), (b'UG4', b'UG4')], max_length=5)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=5)),
                ('rollno', models.CharField(max_length=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField()),
                ('fileuploaded', models.FileField(upload_to=b'/evaluation/submissions/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.Project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekno', models.PositiveIntegerField(default=0)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.Week'),
        ),
        migrations.AddField(
            model_name='evalgroup',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.EvalPanel'),
        ),
    ]
