# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 12:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0003_auto_20160121_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTPGroupWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField()),
                ('endtime', models.DateField()),
                ('submitdeadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BTPProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
                ('faculty', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPProject')),
            ],
        ),
        migrations.RenameField(
            model_name='btpweek',
            old_name='enddate',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='btpweek',
            old_name='startdate',
            new_name='starttime',
        ),
        migrations.RemoveField(
            model_name='btpsubmission',
            name='project',
        ),
        migrations.AlterField(
            model_name='btpsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='btpsubmission',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPGroupWeek'),
        ),
        migrations.AddField(
            model_name='btpgroupweek',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPProjectGroup'),
        ),
        migrations.AddField(
            model_name='btpgroupweek',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPWeek'),
        ),
        migrations.AddField(
            model_name='btpsubmission',
            name='projectgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btp.BTPProjectGroup'),
        ),
    ]
