# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 10:32
from __future__ import unicode_literals

import btp.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0006_auto_20160128_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('fileupload', models.FileField(upload_to=b'/static/btp/files/')),
            ],
        ),
        
        migrations.AlterField(
            model_name='btpsubmission',
            name='fileuploaded',
            field=models.FileField(upload_to=btp.models.content_file_name),
        ),
    ]
