# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 04:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0008_auto_20160218_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 2, 18, 4, 15, 7, 89609, tzinfo=utc)),
        ),
    ]
