# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 04:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BTPEvalPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='BTPSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField()),
                ('fileuploaded', models.FileField(upload_to=b'/btp/evaluation/submissions/')),
            ],
        ),
        migrations.RenameModel(
            old_name='EvalGroup',
            new_name='BTPEvalGroup',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='BTPProject',
        ),
        migrations.DeleteModel(
            name='EvalPanel',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='week',
        ),
        migrations.AlterField(
            model_name='btpevalgroup',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPEvalPanel'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='btpsubmission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPProject'),
        ),
        migrations.AddField(
            model_name='btpsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='btpsubmission',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.Week'),
        ),
    ]
