# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0004_auto_20160127_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTPSetWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateField()),
                ('endtime', models.DateField()),
                ('submitdeadline', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='BTPEvalGroup',
            new_name='BTPEvalSet',
        ),
        migrations.RemoveField(
            model_name='btpgroupweek',
            name='group',
        ),
        migrations.RemoveField(
            model_name='btpgroupweek',
            name='week',
        ),
        migrations.RenameField(
            model_name='btpevalset',
            old_name='projects',
            new_name='projectgroups',
        ),
        migrations.AlterField(
            model_name='btpsubmission',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPSetWeek'),
        ),
        migrations.DeleteModel(
            name='BTPGroupWeek',
        ),
        migrations.AddField(
            model_name='btpsetweek',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPEvalSet'),
        ),
        migrations.AddField(
            model_name='btpsetweek',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.BTPWeek'),
        ),
    ]
